name: Package

on:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to GitHub Packages Apache Maven
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_USERNAME: ${{ secrets.USERNAME }}